version: "3.8"

services:
  cache:
    image: 'bitnami/redis:latest'
    env_file: .env
    networks:
      - default
    ports:
    - '7000:7000'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - cache
    networks:
      - default
    ports:
    - "8080:8080"